#!/usr/bin/env zsh

if ! type git > /dev/null; then
	echo "git not found. abort"
	exit 1
fi

source .init.d/include

local base_dir=$(cd $(dirname $0) && pwd)

create_symlink $base_dir

install_zplug
install_tpm

install_nvimrc_files $base_dir
