[[plugins]]
# better status bar
repo = 'itchyny/lightline.vim'
hook_add = 'runtime .nvimrc.d/lightline.vim'

[[plugins]]
# syntax highlighting
repo = 'cespare/vim-toml'

[[plugins]]
# syntax highlighting
repo = 'derekwyatt/vim-scala'

[[plugins]]
# syntax highlighting
repo = 'chikamichi/mediawiki.vim'

[[plugins]]
# makes gvim-only colorschemes work transparently in terminal vim
repo = 'vim-scripts/CSApprox'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    "" NERDTree configuration
    let g:NERDTreeChDirMode=2
    let g:NERDTreeIgnore=['\.rbc$', '\~$', '\.pyc$', '\.db$', '\.sqlite$', '__pycache__']
    let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\.bak$', '\~$']
    let g:NERDTreeShowBookmarks=1
    let g:nerdtree_tabs_focus_on_files=1
    let g:NERDTreeMapOpenInTabSilent = '<RightMouse>'
    let g:NERDTreeWinSize = 50
    set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite

    nnoremap <silent> <F2> :NERDTreeFind<CR>
    nnoremap <silent> <F3> :NERDTreeTabsToggle<CR>
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
depends = ['nerdtree']

[[plugins]]
# displays tags in a window, ordered by scope
# http://majutsushi.github.io/tagbar/
repo = 'majutsushi/tagbar'
hook_add = '''
    nmap <silent> <F4> :TagbarToggle<CR>

    let g:tagbar_autofocus = 1

    let g:tagbar_type_ruby = {
        \ 'kinds' : [
            \ 'm:modules',
            \ 'c:classes',
            \ 'd:describes',
            \ 'C:contexts',
            \ 'f:methods',
            \ 'F:singleton methods'
        \ ]
    \ }
'''

[[plugins]]
# displays the indention levels with thin vertical lines
repo = 'Yggdroot/indentLine'

[[plugins]]
# handles extra whitespaces
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
# shows a git diff in the gutter (sign column) and stages/undoes hunks.
repo = 'airblade/vim-gitgutter'

[[plugins]]
# detects file type under the cursor according to context
repo = 'Shougo/context_filetype.vim'

[[plugins]]
# syntax highlighting for context
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
# git in vim
repo = 'tpope/vim-fugitive'

[[plugins]]
# better word object handling
repo = 'tpope/vim-surround'

[[plugins]]
# better '.' command
repo = 'tpope/vim-repeat'

[[plugins]]
# comment-out plugin
repo = 'tpope/vim-commentary'

[[plugins]]
# A solid language pack (syntax, indent, etc)
repo = 'sheerun/vim-polyglot'

